version: '3.8'
services:
  web:
    image: php:8.1-apache
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    command: >
      bash -lc "a2enmod rewrite && \
                sed -ri 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf && \
                apache2-foreground"