version: '3'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./saves:/var/www/html/saves
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 